import type { NextPage } from 'next'
import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux'
import { decrement, increment, incrementAmount } from '../redux/slices/counterSlice'


const Home: NextPage = () => {
  const dispatch = useDispatch()
  const counter:any= useSelector<any>(state=>state.counter)
  console.log(counter.value)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
            <h1>Belajar Redux</h1>
            Count : {counter?.value}
      </div>
      <div>
        <button onClick={()=>dispatch(increment())}>+</button>
        <button onClick={()=>dispatch(decrement())}>-</button>
        <button onClick={()=>dispatch(incrementAmount(20))}>+20</button>

      </div>
     
    </div>
  )
}

export default Home
